require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PlateauSessionsController do

  def mock_plateau_session(stubs={})
    @mock_plateau_session ||= mock_model(PlateauSession, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all plateau_sessions as @plateau_sessions" do
      PlateauSession.stub(:all) { [mock_plateau_session] }
      get :index
      assigns(:plateau_sessions).should eq([mock_plateau_session])
    end
  end

  describe "GET show" do
    it "assigns the requested plateau_session as @plateau_session" do
      PlateauSession.stub(:find).with("37") { mock_plateau_session }
      get :show, :id => "37"
      assigns(:plateau_session).should be(mock_plateau_session)
    end
  end

  describe "GET new" do
    it "assigns a new plateau_session as @plateau_session" do
      PlateauSession.stub(:new) { mock_plateau_session }
      get :new
      assigns(:plateau_session).should be(mock_plateau_session)
    end
  end

  describe "GET edit" do
    it "assigns the requested plateau_session as @plateau_session" do
      PlateauSession.stub(:find).with("37") { mock_plateau_session }
      get :edit, :id => "37"
      assigns(:plateau_session).should be(mock_plateau_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created plateau_session as @plateau_session" do
        PlateauSession.stub(:new).with({'these' => 'params'}) { mock_plateau_session(:save => true) }
        post :create, :plateau_session => {'these' => 'params'}
        assigns(:plateau_session).should be(mock_plateau_session)
      end

      it "redirects to the created plateau_session" do
        PlateauSession.stub(:new) { mock_plateau_session(:save => true) }
        post :create, :plateau_session => {}
        response.should redirect_to(plateau_session_url(mock_plateau_session))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plateau_session as @plateau_session" do
        PlateauSession.stub(:new).with({'these' => 'params'}) { mock_plateau_session(:save => false) }
        post :create, :plateau_session => {'these' => 'params'}
        assigns(:plateau_session).should be(mock_plateau_session)
      end

      it "re-renders the 'new' template" do
        PlateauSession.stub(:new) { mock_plateau_session(:save => false) }
        post :create, :plateau_session => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plateau_session" do
        PlateauSession.stub(:find).with("37") { mock_plateau_session }
        mock_plateau_session.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :plateau_session => {'these' => 'params'}
      end

      it "assigns the requested plateau_session as @plateau_session" do
        PlateauSession.stub(:find) { mock_plateau_session(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:plateau_session).should be(mock_plateau_session)
      end

      it "redirects to the plateau_session" do
        PlateauSession.stub(:find) { mock_plateau_session(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(plateau_session_url(mock_plateau_session))
      end
    end

    describe "with invalid params" do
      it "assigns the plateau_session as @plateau_session" do
        PlateauSession.stub(:find) { mock_plateau_session(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:plateau_session).should be(mock_plateau_session)
      end

      it "re-renders the 'edit' template" do
        PlateauSession.stub(:find) { mock_plateau_session(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plateau_session" do
      PlateauSession.stub(:find).with("37") { mock_plateau_session }
      mock_plateau_session.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the plateau_sessions list" do
      PlateauSession.stub(:find) { mock_plateau_session }
      delete :destroy, :id => "1"
      response.should redirect_to(plateau_sessions_url)
    end
  end

end
