require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VehiculesController do

  def mock_vehicule(stubs={})
    @mock_vehicule ||= mock_model(Vehicule, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all vehicules as @vehicules" do
      Vehicule.stub(:all) { [mock_vehicule] }
      get :index
      assigns(:vehicules).should eq([mock_vehicule])
    end
  end

  describe "GET show" do
    it "assigns the requested vehicule as @vehicule" do
      Vehicule.stub(:find).with("37") { mock_vehicule }
      get :show, :id => "37"
      assigns(:vehicule).should be(mock_vehicule)
    end
  end

  describe "GET new" do
    it "assigns a new vehicule as @vehicule" do
      Vehicule.stub(:new) { mock_vehicule }
      get :new
      assigns(:vehicule).should be(mock_vehicule)
    end
  end

  describe "GET edit" do
    it "assigns the requested vehicule as @vehicule" do
      Vehicule.stub(:find).with("37") { mock_vehicule }
      get :edit, :id => "37"
      assigns(:vehicule).should be(mock_vehicule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created vehicule as @vehicule" do
        Vehicule.stub(:new).with({'these' => 'params'}) { mock_vehicule(:save => true) }
        post :create, :vehicule => {'these' => 'params'}
        assigns(:vehicule).should be(mock_vehicule)
      end

      it "redirects to the created vehicule" do
        Vehicule.stub(:new) { mock_vehicule(:save => true) }
        post :create, :vehicule => {}
        response.should redirect_to(vehicule_url(mock_vehicule))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vehicule as @vehicule" do
        Vehicule.stub(:new).with({'these' => 'params'}) { mock_vehicule(:save => false) }
        post :create, :vehicule => {'these' => 'params'}
        assigns(:vehicule).should be(mock_vehicule)
      end

      it "re-renders the 'new' template" do
        Vehicule.stub(:new) { mock_vehicule(:save => false) }
        post :create, :vehicule => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vehicule" do
        Vehicule.stub(:find).with("37") { mock_vehicule }
        mock_vehicule.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :vehicule => {'these' => 'params'}
      end

      it "assigns the requested vehicule as @vehicule" do
        Vehicule.stub(:find) { mock_vehicule(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:vehicule).should be(mock_vehicule)
      end

      it "redirects to the vehicule" do
        Vehicule.stub(:find) { mock_vehicule(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(vehicule_url(mock_vehicule))
      end
    end

    describe "with invalid params" do
      it "assigns the vehicule as @vehicule" do
        Vehicule.stub(:find) { mock_vehicule(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:vehicule).should be(mock_vehicule)
      end

      it "re-renders the 'edit' template" do
        Vehicule.stub(:find) { mock_vehicule(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vehicule" do
      Vehicule.stub(:find).with("37") { mock_vehicule }
      mock_vehicule.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the vehicules list" do
      Vehicule.stub(:find) { mock_vehicule }
      delete :destroy, :id => "1"
      response.should redirect_to(vehicules_url)
    end
  end

end
